apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: mysql
        image: mysql:8.0.32
        env:
          - name: MARIADB_ROOT_PASSWORD
            value: "dbpassword"
          - name: MYSQL_DATABASE
            value: "example"
        ports:
        - containerPort: 3306
